#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

"${SCRIPT_DIR}/scripts/00-installer-kind.sh"
"${SCRIPT_DIR}/scripts/01-mcp-lifecycle-operator.sh"
"${SCRIPT_DIR}/scripts/02-gateway-api-istio.sh"
"${SCRIPT_DIR}/scripts/03-mcp-gateway.sh"
"${SCRIPT_DIR}/scripts/04-mcp-launcher.sh"

echo ""
echo "========================================"
echo "🎉 MCP-Box Installation Complete!"
echo "========================================"
echo ""
echo "📦 Installed Components:"
echo "  ✅ Kind cluster with NodePort mapping (host port 7001)"
echo "  ✅ MCP Lifecycle Operator"
echo "  ✅ Gateway API CRDs + Istio"
echo "  ✅ MCP Gateway (v${MCP_GATEWAY_VERSION:-0.5.1})"
echo "  ✅ MCP Launcher (Web UI)"
echo ""
echo "🚀 Next Steps:"
echo ""
echo "  🌐 MCP Gateway (ready to use — no port-forward needed):"
echo "     http://localhost:7001/mcp"
echo ""
echo "  🖥️  MCP Launcher UI (requires port-forward):"
echo "     kubectl port-forward -n mcp-system svc/mcp-launcher 9090:8080"
echo "     → http://localhost:9090"
echo ""
echo "  🔍 MCP Inspector (optional):"
echo "     podman run --rm --network host ghcr.io/modelcontextprotocol/inspector:latest"
echo "     → http://localhost:6274"
echo ""
echo "========================================"
